version: '2.0'
services:
  hadoop-namenode:
    build:
      context: ./hadoop-master
      dockerfile: Dockerfile
    image: trex/hadoop-master
    container_name: master.trex.com
    hostname: master.trex.com
    environment:
      HADOOP_MASTER: master.trex.com
      HADOOP_SLAVE: slave1.trex.com slave2.trex.com
  hadoop-datanode-1:
    build:
      context: ./hadoop-slave
      dockerfile: Dockerfile
    image: trex/hadoop-slave
    container_name: slave1.trex.com
    hostname: slave1.trex.com
    environment:
      HADOOP_MASTER: master.trex.com
      HADOOP_SLAVE: slave1.trex.com slave2.trex.com
  hadoop-datanode-2:
    build:
      context: ./hadoop-slave
      dockerfile: Dockerfile
    image: trex/hadoop-slave
    container_name: slave2.trex.com
    hostname: slave2.trex.com
    environment:
      HADOOP_MASTER: master.trex.com
      HADOOP_SLAVE: slave1.trex.com slave2.trex.com

