version: '2.0'
services:
  hadoop-namenode:
    build:
      context: ./hadoop-master
      dockerfile: Dockerfile
    image: trex/hadoop-master
    container_name: master
    hostname: master.test.com
  hadoop-datanode-1:
    build:
      context: ./hadoop-slave
      dockerfile: Dockerfile
    image: trex/hadoop-slave
    container_name: slave1
    hostname: slave1.test.com
  hadoop-datanode-2:
    build:
      context: ./hadoop-slave
      dockerfile: Dockerfile
    image: trex/hadoop-slave
    container_name: slave2
    hostname: slave2.test.com
